### ISSUE TITLE
About the memory consumption

### ISSUE THREAD

**Issue by nnnwyn** [hpcaitech/FastFold#7]
Hi, When i read the support information of AlphaFold2, I got confused about the "1.11.8 Reducing the memory consumption". It said that when using the technique called gradient checkpoint, the memory consumption can be reduced to square size from cubic size when training. And when making inference, the set of the chunk of layers can also change the memory from cubic size into square size. I don't know why this can be done? Can anyone give me a hand?

**Comment by Shenggan** [comment]
For Training, AlphaFold uses the Activation Checkpoint, which can be found in [PyTorch's checkpoint interface](https://pytorch.org/docs/stable/checkpoint.html) and [this paper](https://arxiv.org/abs/1604.06174). 

For Inference, because the representation in AlphaFold has two sequential dimensions, while doing the computation in one direction, the other direction can be seen as the batch dimension, so it can be computed sequentially in chunks in this dimension, thus reducing the temporary memory needed for the intermediate computation process.
